// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlatBuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoolSaveDataUnit struct {
	_tab flatbuffers.Table
}

func GetRootAsBoolSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *BoolSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoolSaveDataUnit{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoolSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoolSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *BoolSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoolSaveDataUnit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoolSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoolSaveDataUnit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoolSaveDataUnit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoolSaveDataUnit) Idtype() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoolSaveDataUnit) MutateIdtype(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *BoolSaveDataUnit) UnitId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BoolSaveDataUnit) MutateUnitId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *BoolSaveDataUnit) ValueData(j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetBool(a + flatbuffers.UOffsetT(j*1))
	}
	return false
}

func (rcv *BoolSaveDataUnit) ValueDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BoolSaveDataUnit) MutateValueData(j int, n bool) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateBool(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func BoolSaveDataUnitStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func BoolSaveDataUnitAddIdtype(builder *flatbuffers.Builder, idtype uint32) {
	builder.PrependUint32Slot(0, idtype, 0)
}
func BoolSaveDataUnitAddUnitId(builder *flatbuffers.Builder, unitId uint32) {
	builder.PrependUint32Slot(1, unitId, 0)
}
func BoolSaveDataUnitAddValueData(builder *flatbuffers.Builder, valueData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(valueData), 0)
}
func BoolSaveDataUnitStartValueDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BoolSaveDataUnitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
