// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlatBuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IntSaveDataUnit struct {
	_tab flatbuffers.Table
}

func GetRootAsIntSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *IntSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IntSaveDataUnit{}
	x.Init(buf, n+offset)
	return x
}

func FinishIntSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIntSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *IntSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IntSaveDataUnit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIntSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IntSaveDataUnit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IntSaveDataUnit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IntSaveDataUnit) Idtype() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IntSaveDataUnit) MutateIdtype(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *IntSaveDataUnit) UnitId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IntSaveDataUnit) MutateUnitId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *IntSaveDataUnit) ValueData(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *IntSaveDataUnit) ValueDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IntSaveDataUnit) MutateValueData(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func IntSaveDataUnitStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func IntSaveDataUnitAddIdtype(builder *flatbuffers.Builder, idtype uint32) {
	builder.PrependUint32Slot(0, idtype, 0)
}
func IntSaveDataUnitAddUnitId(builder *flatbuffers.Builder, unitId uint32) {
	builder.PrependUint32Slot(1, unitId, 0)
}
func IntSaveDataUnitAddValueData(builder *flatbuffers.Builder, valueData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(valueData), 0)
}
func IntSaveDataUnitStartValueDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func IntSaveDataUnitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
