// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlatBuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShortSaveDataUnit struct {
	_tab flatbuffers.Table
}

func GetRootAsShortSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *ShortSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ShortSaveDataUnit{}
	x.Init(buf, n+offset)
	return x
}

func FinishShortSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsShortSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *ShortSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ShortSaveDataUnit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedShortSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ShortSaveDataUnit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShortSaveDataUnit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ShortSaveDataUnit) Idtype() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ShortSaveDataUnit) MutateIdtype(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ShortSaveDataUnit) UnitId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ShortSaveDataUnit) MutateUnitId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *ShortSaveDataUnit) ValueData(j int) int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *ShortSaveDataUnit) ValueDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ShortSaveDataUnit) MutateValueData(j int, n int16) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt16(a+flatbuffers.UOffsetT(j*2), n)
	}
	return false
}

func ShortSaveDataUnitStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ShortSaveDataUnitAddIdtype(builder *flatbuffers.Builder, idtype uint32) {
	builder.PrependUint32Slot(0, idtype, 0)
}
func ShortSaveDataUnitAddUnitId(builder *flatbuffers.Builder, unitId uint32) {
	builder.PrependUint32Slot(1, unitId, 0)
}
func ShortSaveDataUnitAddValueData(builder *flatbuffers.Builder, valueData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(valueData), 0)
}
func ShortSaveDataUnitStartValueDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func ShortSaveDataUnitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
