// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FlatBuffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UByteSaveDataUnit struct {
	_tab flatbuffers.Table
}

func GetRootAsUByteSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *UByteSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UByteSaveDataUnit{}
	x.Init(buf, n+offset)
	return x
}

func FinishUByteSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUByteSaveDataUnit(buf []byte, offset flatbuffers.UOffsetT) *UByteSaveDataUnit {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UByteSaveDataUnit{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUByteSaveDataUnitBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UByteSaveDataUnit) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UByteSaveDataUnit) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UByteSaveDataUnit) Idtype() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UByteSaveDataUnit) MutateIdtype(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *UByteSaveDataUnit) UnitId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UByteSaveDataUnit) MutateUnitId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *UByteSaveDataUnit) ValueData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *UByteSaveDataUnit) ValueDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *UByteSaveDataUnit) ValueDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UByteSaveDataUnit) MutateValueData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func UByteSaveDataUnitStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UByteSaveDataUnitAddIdtype(builder *flatbuffers.Builder, idtype uint32) {
	builder.PrependUint32Slot(0, idtype, 0)
}
func UByteSaveDataUnitAddUnitId(builder *flatbuffers.Builder, unitId uint32) {
	builder.PrependUint32Slot(1, unitId, 0)
}
func UByteSaveDataUnitAddValueData(builder *flatbuffers.Builder, valueData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(valueData), 0)
}
func UByteSaveDataUnitStartValueDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func UByteSaveDataUnitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
